-- PharmaSaathi - invoice intake & downstream analytics schema (SQLite)
--
-- Design notes:
--  - invoice_receipts is the single source of truth for intake; everything
--    else here is DERIVED from it, generated by the backend at insert time
--    (see server/derive.ts) - never hand-edited.
--  - facilities / medicines mirror the frontend's src/data.ts catalog (kept
--    in sync by hand in server/catalog.ts) so receipts can carry real
--    foreign keys instead of loose strings.
--  - This schema is independent of the frontend's in-memory simulation
--    (src/simulate.ts). The frontend still owns the live, richer
--    stock/trust math for the current session; this database is the
--    durable record that survives a page reload and the source for each
--    module's historical/derived view.

CREATE TABLE IF NOT EXISTS facilities (
  id   TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  hub_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS medicines (
  id       TEXT PRIMARY KEY,
  name     TEXT NOT NULL,
  ven      TEXT NOT NULL CHECK (ven IN ('V','E','N')),
  category TEXT NOT NULL
);

-- 1. INVENTORY INTAKE ---------------------------------------------------
CREATE TABLE IF NOT EXISTS invoice_receipts (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  facility_id   TEXT NOT NULL REFERENCES facilities(id),
  medicine_id   TEXT NOT NULL REFERENCES medicines(id),
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  batch_number  TEXT,
  expiry_date   TEXT,              -- 'YYYY-MM-DD', nullable
  received_at   TEXT NOT NULL,     -- ISO datetime the invoice states (or upload time if unstated)
  logged_at     TEXT NOT NULL      -- ISO datetime this row was written
);
CREATE INDEX IF NOT EXISTS idx_receipts_medicine ON invoice_receipts(medicine_id);
CREATE INDEX IF NOT EXISTS idx_receipts_facility ON invoice_receipts(facility_id);

-- 2. EXPIRY WATCH --------------------------------------------------------
CREATE TABLE IF NOT EXISTS expiry_watch_alerts (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  receipt_id    INTEGER NOT NULL REFERENCES invoice_receipts(id),
  facility_id   TEXT NOT NULL REFERENCES facilities(id),
  medicine_id   TEXT NOT NULL REFERENCES medicines(id),
  expiry_date   TEXT NOT NULL,
  days_remaining INTEGER NOT NULL, -- as of logged_at, real wall-clock days
  bucket        TEXT NOT NULL CHECK (bucket IN ('30','60','90')), -- smallest threshold it falls within
  created_at    TEXT NOT NULL
);

-- 3. FACILITY & SUPPLIER TRUST -------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_trust_events (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  facility_id   TEXT NOT NULL REFERENCES facilities(id),
  receipt_id    INTEGER NOT NULL REFERENCES invoice_receipts(id),
  delta         REAL NOT NULL,     -- score nudge from this delivery
  running_score REAL NOT NULL,     -- facility's trust score after this event
  created_at    TEXT NOT NULL
);

-- 4. SEASONAL DEMAND -------------------------------------------------------
CREATE TABLE IF NOT EXISTS seasonal_volume_agg (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  medicine_id    TEXT NOT NULL REFERENCES medicines(id),
  year_month     TEXT NOT NULL,    -- 'YYYY-MM'
  total_qty      INTEGER NOT NULL,
  prior_avg_qty  REAL,             -- avg of the 3 preceding year_months, if any
  pct_change     REAL,
  imbalance_flag INTEGER NOT NULL DEFAULT 0, -- 1 if |pct_change| exceeds threshold
  updated_at     TEXT NOT NULL,
  UNIQUE(medicine_id, year_month)
);

-- 5. EMERGING REGIONAL SIGNALS --------------------------------------------
CREATE TABLE IF NOT EXISTS regional_signal_events (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  hub_id       TEXT NOT NULL,
  ven          TEXT NOT NULL CHECK (ven IN ('V','E','N')),
  window_start TEXT NOT NULL,
  window_end   TEXT NOT NULL,
  total_qty    INTEGER NOT NULL,   -- received in the trailing 7 days
  baseline_qty REAL NOT NULL,      -- trailing 30-day daily average x 7, for comparison
  spike_ratio  REAL NOT NULL,      -- total_qty / baseline_qty
  created_at   TEXT NOT NULL
);

-- 6. REDISTRIBUTION OPPORTUNITIES ------------------------------------------
CREATE TABLE IF NOT EXISTS redistribution_recommendations (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  medicine_id     TEXT NOT NULL REFERENCES medicines(id),
  from_facility_id TEXT NOT NULL REFERENCES facilities(id),
  to_facility_id   TEXT NOT NULL REFERENCES facilities(id),
  reason          TEXT NOT NULL CHECK (reason IN ('short_expiry','overstock')),
  units           INTEGER NOT NULL,
  expiry_date     TEXT,
  status          TEXT NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested','dismissed')),
  created_at      TEXT NOT NULL
);
